[unstable]
codegen-backend = true

[build]
rustflags = "-Zthreads=8"

[target.'cfg(target_os = "linux")']
# mold, if you have GCC 12+
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[resolver]
feature-unification = "workspace"


